### ISSUE TITLE
Question: Is this Directive uses Session tokens ?

### ISSUE THREAD

**Issue by georgefam** [skynet2/ngx-google-places-autocomplete#28]
First Thanks for effort in developing this directive, i had start using it but i have notice i got API calls count per key stroke, and when i read google documentation i notice they mention unless you are using session token the the API calls will be charged by keystroke.

Is your directive using Session tokens ? if not is it possible to add it ? 

https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by aniketpatil32** [comment]
Attention needed to this issue.

**Comment by danilopolani** [comment]
I guess there's a lot of work to do about this, because:

1. You have [to replace](https://github.com/skynet2/ngx-google-places-autocomplete/blob/master/src/ngx-google-places-autocomplete.directive.ts#L37) `Autocomplete` with `AutocompleteService`
2. You have [to listen](https://github.com/skynet2/ngx-google-places-autocomplete/blob/master/src/ngx-google-places-autocomplete.directive.ts#L48) to keypress/keyup/keydown event from native element in order to call the `AutocompleteService`
3. Build a function to show the results, hoping the one provided by Google example is correctly working. As I see online it seems it's not built to provide a "suggestion" system for inputs, because you need to create the whole "popup" under the input, manage clicks and so on
4. Provide the token to use it in the `placeDetail()` request

**Comment by imran23** [comment]
I was using this directive and my client was being billed $$$$$ since every keystroke is billed. I had to ditch this directive and write my own service that utilizes AutocompleteService. If you plan to go that route, I would also suggest using "offset". The "offset" property tells the service to start making API calls after n number of characters have been typed. Using AutocompleteService gives you more control over when to make an API call. You also write code to display the list of returned addresses.

**Comment by danilopolani** [comment]
Thank you Imran, I hate the fact that you have to write your own callback to render the results. Why tf Google doesn't implement `token` for `Autocomplete` I really don't know

**Comment by skynet2** [comment]
As far as that library is just a wrapper for google places autocomplete, it doesn`t use session tokens.
But you should be able to use fields property for customization https://github.com/skynet2/ngx-google-places-autocomplete/issues/36

**Comment by mikeysteele** [comment]
According to this: https://developers.google.com/maps/documentation/javascript/places-autocomplete#session_tokens session tokens are automatically handled by the widget. So in that case this directive is using session tokens.
