### ISSUE TITLE
Location Object

### ISSUE THREAD

**Issue by nikosgram13** [skynet2/ngx-google-places-autocomplete#3]
https://github.com/skynet2/ngx-google-places-autocomplete/blob/3e800ef065661692c4b5b1785b88b5af1a972a31/src/objects/geometry.ts#L4

Hello man, I tried to use ur plugin but I realize that Location object is annotated to es6 Location object.

U should fix this by adding ```import { Location } from "./location";``` on the top of geometry.ts file.

**Comment by skynet2** [comment]
Hey Nikolas,

Good catch. Should be fixed in 1.0.5 ver now.

Thanks,
Stas

**Comment by nikosgram13** [comment]
No worries man, my pleasure.

BTW, on Location object, the google api is returning lat and lng as function, no as variables.

![image](https://user-images.githubusercontent.com/3318873/35755784-8fb5d2fe-0860-11e8-9190-5715d2eeb34a.png)

Kind regards,
Nikolaos.

**Comment by nikosgram13** [comment]
If you want to check google's api, search for `@types/googlemaps`. I can found google's maps api on typescript.

**Comment by skynet2** [comment]
Hey Nikolas, 

Yep, I see, probably the difference was because I generated interfaces based on JSON output.
Thank you for your advice. Had some time today and updated lib to version 2.0 with interfaces from @types/googlemaps.  

https://github.com/skynet2/ngx-google-places-autocomplete/commit/977f059aca525bcabd80138e3eb99dde4873a30d

Thanks,
Stas
